title: Nick Garner # your name (or website title) here
logo: "/images/Logo_NG.png?raw=true" # your photo (or logo) here 
description: > # your text below (remove <br> elements if you don't need line breaks)
  Research Scientist and Data Analyst
  <br><br>
  Enthusiastic about coffee and sleep
  <br><br>
  <a href="https://www.linkedin.com/in/nick-garner-8b31b093/</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
