title: Nick Garner # your name (or website title) here
logo: <img src="/images/CircularHeadshot.png" width="200"/>  # your photo (or logo) here 
description: > # your text below (remove <br> elements if you don't need line breaks)
  Research Scientist and Data Analyst
  <br><br>
  Enthusiastic about coffee and sleep
  <br><br>
  Social Media:
  <a href="https://www.linkedin.com/in/nick-garner-8b31b093/">View my LinkedIn Profile</a> 
  <a href="https://www.researchgate.net/profile/Nicholas-Garner-2/">View my ResearchGate Profile</a> 
  <a href="https://orcid.org/0000-0003-0118-0720/">View my ORCiD</a> 
  <br><br>
  <a href="https://n-garner.github.io/pdf/Resume.pdf">Check out my Resume</a>  
  <br><br>
  
theme: jekyll-theme-minimal
google_analytics: G-XDQC8X280E # your Google Analytics tracking ID here


